import type { Block, Process } from './api'

/** "place order" / "Order Placed" / "record-activity log" → PlaceOrder / OrderPlaced / RecordActivityLog */
export function goIdent(text: string): string {
  const ident = text
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('')
  if (!ident) return 'Unnamed'
  return /^[0-9]/.test(ident) ? `X${ident}` : ident
}

function structBody(block: Block, extra: string[] = []): string {
  const rows = block.fields.map((f) => [goIdent(f.name), f.type.trim() || 'string'])
  const width = Math.max(0, ...rows.map(([n]) => n.length))
  const lines = [...rows.map(([n, t]) => `\t${n.padEnd(width)} ${t}`), ...(rows.length && extra.length ? [''] : []), ...extra]
  return lines.length ? ` {\n${lines.join('\n')}\n}` : '{}'
}

function doc(block: Block): string {
  const lines: string[] = []
  if (block.actor) lines.push(`// Actor: ${block.actor}`)
  for (const h of block.hotspots) lines.push(`// HOTSPOT: ${h}`)
  return lines.length ? `${lines.join('\n')}\n` : ''
}

/**
 * Go for one block, derived from its kind and its connections:
 * a command flowing into an aggregate becomes a method on it that records
 * the aggregate's outgoing events; an event flowing into a policy becomes
 * that policy's handler argument. The mapping is a first cut of the
 * roadmap in PROJECT_OVERVIEW.md, not a finalized spec.
 */
export function generateBlock(block: Block, process: Process): string {
  const byId = new Map(process.blocks.map((b) => [b.id, b]))
  const from = (kind: Block['kind']) =>
    process.connections
      .filter((c) => c.targetId === block.id)
      .map((c) => byId.get(c.sourceId))
      .filter((b): b is Block => b?.kind === kind)
  const to = (kind: Block['kind']) =>
    process.connections
      .filter((c) => c.sourceId === block.id)
      .map((c) => byId.get(c.targetId))
      .filter((b): b is Block => b?.kind === kind)
  const name = goIdent(block.title)

  switch (block.kind) {
    case 'command':
    case 'event':
    case 'readmodel':
      return `${doc(block)}type ${name} struct${structBody(block)}`

    case 'aggregate': {
      const events = to('event')
      const methods = from('command').map((cmd) => {
        const cmdName = goIdent(cmd.title)
        const records = events.map((e) => `\ta.record(${goIdent(e.title)}{})`)
        return `func (a *${name}) ${cmdName}(cmd ${cmdName}) error {\n\t// TODO: enforce ${name} invariants\n${[...records, '\treturn nil'].join('\n')}\n}`
      })
      return [
        `${doc(block)}type ${name} struct${structBody(block, ['\tevents []any'])}`,
        ...methods,
        `func (a *${name}) record(e any) { a.events = append(a.events, e) }`,
        `type ${name}Repository interface {\n\tLoad(ctx context.Context, id string) (*${name}, error)\n\tSave(ctx context.Context, a *${name}) error\n}`,
      ].join('\n\n')
    }

    case 'policy': {
      const triggers = from('event')
      const arg = triggers.length === 1 ? `e ${goIdent(triggers[0].title)}` : 'e any'
      const when = triggers.length ? `Whenever ${triggers.map((t) => t.title).join(' or ')}, ` : ''
      return `${doc(block)}// ${name}: ${when}${block.title.toLowerCase()}.\nfunc ${name}(ctx context.Context, ${arg}) error {\n\treturn nil\n}`
    }

    case 'system':
      return `${doc(block)}// ${block.title} is an external system.\ntype ${name} interface{}`
  }
}

/** A single .go file for the whole process, in flow-friendly kind order. */
export function generateProcess(process: Process): string {
  const order: Block['kind'][] = ['readmodel', 'command', 'aggregate', 'event', 'policy', 'system']
  const blocks = [...process.blocks].sort((a, b) => order.indexOf(a.kind) - order.indexOf(b.kind) || a.x - b.x)
  const pkg = goIdent(process.name).toLowerCase()
  const usesContext = blocks.some((b) => b.kind === 'aggregate' || b.kind === 'policy')
  return [
    `// Code generated by Stormm from process "${process.name}".\npackage ${pkg}`,
    ...(usesContext ? ['import "context"'] : []),
    ...blocks.map((b) => generateBlock(b, process)),
  ].join('\n\n') + '\n'
}
